//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5472
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 1591

namespace Evolucao {
    
    
    /// <summary>
    ///Represents a strongly typed in-memory cache of data.
    ///</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
    [global::System.Serializable()]
    [global::System.ComponentModel.DesignerCategoryAttribute("code")]
    [global::System.ComponentModel.ToolboxItem(true)]
    [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedDataSetSchema")]
    [global::System.Xml.Serialization.XmlRootAttribute("dsRequisicao")]
    [global::System.ComponentModel.Design.HelpKeywordAttribute("vs.data.DataSet")]
    public partial class dsRequisicao : global::System.Data.DataSet {
        
        private REQUISICOESDataTable tableREQUISICOES;
        
        private ITENS_REQUISICAODataTable tableITENS_REQUISICAO;
        
        private global::System.Data.SchemaSerializationMode _schemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public dsRequisicao() {
            this.BeginInit();
            this.InitClass();
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            base.Relations.CollectionChanged += schemaChangedHandler;
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected dsRequisicao(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                base(info, context, false) {
            if ((this.IsBinarySerialized(info, context) == true)) {
                this.InitVars(false);
                global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler1 = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
                this.Tables.CollectionChanged += schemaChangedHandler1;
                this.Relations.CollectionChanged += schemaChangedHandler1;
                return;
            }
            string strSchema = ((string)(info.GetValue("XmlSchema", typeof(string))));
            if ((this.DetermineSchemaSerializationMode(info, context) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
                if ((ds.Tables["REQUISICOES"] != null)) {
                    base.Tables.Add(new REQUISICOESDataTable(ds.Tables["REQUISICOES"]));
                }
                if ((ds.Tables["ITENS_REQUISICAO"] != null)) {
                    base.Tables.Add(new ITENS_REQUISICAODataTable(ds.Tables["ITENS_REQUISICAO"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
            }
            this.GetSerializationData(info, context);
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.Browsable(false)]
        [global::System.ComponentModel.DesignerSerializationVisibility(global::System.ComponentModel.DesignerSerializationVisibility.Content)]
        public REQUISICOESDataTable REQUISICOES {
            get {
                return this.tableREQUISICOES;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.Browsable(false)]
        [global::System.ComponentModel.DesignerSerializationVisibility(global::System.ComponentModel.DesignerSerializationVisibility.Content)]
        public ITENS_REQUISICAODataTable ITENS_REQUISICAO {
            get {
                return this.tableITENS_REQUISICAO;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.BrowsableAttribute(true)]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Visible)]
        public override global::System.Data.SchemaSerializationMode SchemaSerializationMode {
            get {
                return this._schemaSerializationMode;
            }
            set {
                this._schemaSerializationMode = value;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataTableCollection Tables {
            get {
                return base.Tables;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataRelationCollection Relations {
            get {
                return base.Relations;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override void InitializeDerivedDataSet() {
            this.BeginInit();
            this.InitClass();
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public override global::System.Data.DataSet Clone() {
            dsRequisicao cln = ((dsRequisicao)(base.Clone()));
            cln.InitVars();
            cln.SchemaSerializationMode = this.SchemaSerializationMode;
            return cln;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override bool ShouldSerializeTables() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override bool ShouldSerializeRelations() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override void ReadXmlSerializable(global::System.Xml.XmlReader reader) {
            if ((this.DetermineSchemaSerializationMode(reader) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                this.Reset();
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXml(reader);
                if ((ds.Tables["REQUISICOES"] != null)) {
                    base.Tables.Add(new REQUISICOESDataTable(ds.Tables["REQUISICOES"]));
                }
                if ((ds.Tables["ITENS_REQUISICAO"] != null)) {
                    base.Tables.Add(new ITENS_REQUISICAODataTable(ds.Tables["ITENS_REQUISICAO"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXml(reader);
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override global::System.Xml.Schema.XmlSchema GetSchemaSerializable() {
            global::System.IO.MemoryStream stream = new global::System.IO.MemoryStream();
            this.WriteXmlSchema(new global::System.Xml.XmlTextWriter(stream, null));
            stream.Position = 0;
            return global::System.Xml.Schema.XmlSchema.Read(new global::System.Xml.XmlTextReader(stream), null);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        internal void InitVars() {
            this.InitVars(true);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        internal void InitVars(bool initTable) {
            this.tableREQUISICOES = ((REQUISICOESDataTable)(base.Tables["REQUISICOES"]));
            if ((initTable == true)) {
                if ((this.tableREQUISICOES != null)) {
                    this.tableREQUISICOES.InitVars();
                }
            }
            this.tableITENS_REQUISICAO = ((ITENS_REQUISICAODataTable)(base.Tables["ITENS_REQUISICAO"]));
            if ((initTable == true)) {
                if ((this.tableITENS_REQUISICAO != null)) {
                    this.tableITENS_REQUISICAO.InitVars();
                }
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void InitClass() {
            this.DataSetName = "dsRequisicao";
            this.Prefix = "";
            this.Namespace = "http://tempuri.org/dsRequisicao.xsd";
            this.EnforceConstraints = true;
            this.SchemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
            this.tableREQUISICOES = new REQUISICOESDataTable();
            base.Tables.Add(this.tableREQUISICOES);
            this.tableITENS_REQUISICAO = new ITENS_REQUISICAODataTable();
            base.Tables.Add(this.tableITENS_REQUISICAO);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private bool ShouldSerializeREQUISICOES() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private bool ShouldSerializeITENS_REQUISICAO() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void SchemaChanged(object sender, global::System.ComponentModel.CollectionChangeEventArgs e) {
            if ((e.Action == global::System.ComponentModel.CollectionChangeAction.Remove)) {
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedDataSetSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
            dsRequisicao ds = new dsRequisicao();
            global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
            global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
            global::System.Xml.Schema.XmlSchemaAny any = new global::System.Xml.Schema.XmlSchemaAny();
            any.Namespace = ds.Namespace;
            sequence.Items.Add(any);
            type.Particle = sequence;
            global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
            if (xs.Contains(dsSchema.TargetNamespace)) {
                global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                try {
                    global::System.Xml.Schema.XmlSchema schema = null;
                    dsSchema.Write(s1);
                    for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                        schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                        s2.SetLength(0);
                        schema.Write(s2);
                        if ((s1.Length == s2.Length)) {
                            s1.Position = 0;
                            s2.Position = 0;
                            for (; ((s1.Position != s1.Length) 
                                        && (s1.ReadByte() == s2.ReadByte())); ) {
                                ;
                            }
                            if ((s1.Position == s1.Length)) {
                                return type;
                            }
                        }
                    }
                }
                finally {
                    if ((s1 != null)) {
                        s1.Close();
                    }
                    if ((s2 != null)) {
                        s2.Close();
                    }
                }
            }
            xs.Add(dsSchema);
            return type;
        }
        
        public delegate void REQUISICOESRowChangeEventHandler(object sender, REQUISICOESRowChangeEvent e);
        
        public delegate void ITENS_REQUISICAORowChangeEventHandler(object sender, ITENS_REQUISICAORowChangeEvent e);
        
        /// <summary>
        ///Represents the strongly named DataTable class.
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
        [global::System.Serializable()]
        [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedTableSchema")]
        public partial class REQUISICOESDataTable : global::System.Data.DataTable, global::System.Collections.IEnumerable {
            
            private global::System.Data.DataColumn columnCOD_REQUISICAO;
            
            private global::System.Data.DataColumn columnREQUISITANTE_REQUISICAO;
            
            private global::System.Data.DataColumn columnSETOR_REQUISICAO;
            
            private global::System.Data.DataColumn columnOBS_REQUISICAO;
            
            private global::System.Data.DataColumn columnDATA_REQUISICAO;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public REQUISICOESDataTable() {
                this.TableName = "REQUISICOES";
                this.BeginInit();
                this.InitClass();
                this.EndInit();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal REQUISICOESDataTable(global::System.Data.DataTable table) {
                this.TableName = table.TableName;
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected REQUISICOESDataTable(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                    base(info, context) {
                this.InitVars();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn COD_REQUISICAOColumn {
                get {
                    return this.columnCOD_REQUISICAO;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn REQUISITANTE_REQUISICAOColumn {
                get {
                    return this.columnREQUISITANTE_REQUISICAO;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn SETOR_REQUISICAOColumn {
                get {
                    return this.columnSETOR_REQUISICAO;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn OBS_REQUISICAOColumn {
                get {
                    return this.columnOBS_REQUISICAO;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn DATA_REQUISICAOColumn {
                get {
                    return this.columnDATA_REQUISICAO;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public REQUISICOESRow this[int index] {
                get {
                    return ((REQUISICOESRow)(this.Rows[index]));
                }
            }
            
            public event REQUISICOESRowChangeEventHandler REQUISICOESRowChanging;
            
            public event REQUISICOESRowChangeEventHandler REQUISICOESRowChanged;
            
            public event REQUISICOESRowChangeEventHandler REQUISICOESRowDeleting;
            
            public event REQUISICOESRowChangeEventHandler REQUISICOESRowDeleted;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void AddREQUISICOESRow(REQUISICOESRow row) {
                this.Rows.Add(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public REQUISICOESRow AddREQUISICOESRow(int COD_REQUISICAO, string REQUISITANTE_REQUISICAO, string SETOR_REQUISICAO, string OBS_REQUISICAO, System.DateTime DATA_REQUISICAO) {
                REQUISICOESRow rowREQUISICOESRow = ((REQUISICOESRow)(this.NewRow()));
                object[] columnValuesArray = new object[] {
                        COD_REQUISICAO,
                        REQUISITANTE_REQUISICAO,
                        SETOR_REQUISICAO,
                        OBS_REQUISICAO,
                        DATA_REQUISICAO};
                rowREQUISICOESRow.ItemArray = columnValuesArray;
                this.Rows.Add(rowREQUISICOESRow);
                return rowREQUISICOESRow;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public REQUISICOESRow FindByCOD_REQUISICAO(int COD_REQUISICAO) {
                return ((REQUISICOESRow)(this.Rows.Find(new object[] {
                            COD_REQUISICAO})));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public virtual global::System.Collections.IEnumerator GetEnumerator() {
                return this.Rows.GetEnumerator();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public override global::System.Data.DataTable Clone() {
                REQUISICOESDataTable cln = ((REQUISICOESDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override global::System.Data.DataTable CreateInstance() {
                return new REQUISICOESDataTable();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal void InitVars() {
                this.columnCOD_REQUISICAO = base.Columns["COD_REQUISICAO"];
                this.columnREQUISITANTE_REQUISICAO = base.Columns["REQUISITANTE_REQUISICAO"];
                this.columnSETOR_REQUISICAO = base.Columns["SETOR_REQUISICAO"];
                this.columnOBS_REQUISICAO = base.Columns["OBS_REQUISICAO"];
                this.columnDATA_REQUISICAO = base.Columns["DATA_REQUISICAO"];
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            private void InitClass() {
                this.columnCOD_REQUISICAO = new global::System.Data.DataColumn("COD_REQUISICAO", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnCOD_REQUISICAO);
                this.columnREQUISITANTE_REQUISICAO = new global::System.Data.DataColumn("REQUISITANTE_REQUISICAO", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnREQUISITANTE_REQUISICAO);
                this.columnSETOR_REQUISICAO = new global::System.Data.DataColumn("SETOR_REQUISICAO", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnSETOR_REQUISICAO);
                this.columnOBS_REQUISICAO = new global::System.Data.DataColumn("OBS_REQUISICAO", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnOBS_REQUISICAO);
                this.columnDATA_REQUISICAO = new global::System.Data.DataColumn("DATA_REQUISICAO", typeof(global::System.DateTime), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnDATA_REQUISICAO);
                this.Constraints.Add(new global::System.Data.UniqueConstraint("Constraint1", new global::System.Data.DataColumn[] {
                                this.columnCOD_REQUISICAO}, true));
                this.columnCOD_REQUISICAO.AllowDBNull = false;
                this.columnCOD_REQUISICAO.Unique = true;
                this.columnREQUISITANTE_REQUISICAO.MaxLength = 200;
                this.columnSETOR_REQUISICAO.MaxLength = 200;
                this.columnOBS_REQUISICAO.MaxLength = 250;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public REQUISICOESRow NewREQUISICOESRow() {
                return ((REQUISICOESRow)(this.NewRow()));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override global::System.Data.DataRow NewRowFromBuilder(global::System.Data.DataRowBuilder builder) {
                return new REQUISICOESRow(builder);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override global::System.Type GetRowType() {
                return typeof(REQUISICOESRow);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowChanged(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.REQUISICOESRowChanged != null)) {
                    this.REQUISICOESRowChanged(this, new REQUISICOESRowChangeEvent(((REQUISICOESRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowChanging(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.REQUISICOESRowChanging != null)) {
                    this.REQUISICOESRowChanging(this, new REQUISICOESRowChangeEvent(((REQUISICOESRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowDeleted(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.REQUISICOESRowDeleted != null)) {
                    this.REQUISICOESRowDeleted(this, new REQUISICOESRowChangeEvent(((REQUISICOESRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowDeleting(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.REQUISICOESRowDeleting != null)) {
                    this.REQUISICOESRowDeleting(this, new REQUISICOESRowChangeEvent(((REQUISICOESRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void RemoveREQUISICOESRow(REQUISICOESRow row) {
                this.Rows.Remove(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedTableSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
                global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
                global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
                dsRequisicao ds = new dsRequisicao();
                global::System.Xml.Schema.XmlSchemaAny any1 = new global::System.Xml.Schema.XmlSchemaAny();
                any1.Namespace = "http://www.w3.org/2001/XMLSchema";
                any1.MinOccurs = new decimal(0);
                any1.MaxOccurs = decimal.MaxValue;
                any1.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any1);
                global::System.Xml.Schema.XmlSchemaAny any2 = new global::System.Xml.Schema.XmlSchemaAny();
                any2.Namespace = "urn:schemas-microsoft-com:xml-diffgram-v1";
                any2.MinOccurs = new decimal(1);
                any2.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any2);
                global::System.Xml.Schema.XmlSchemaAttribute attribute1 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute1.Name = "namespace";
                attribute1.FixedValue = ds.Namespace;
                type.Attributes.Add(attribute1);
                global::System.Xml.Schema.XmlSchemaAttribute attribute2 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute2.Name = "tableTypeName";
                attribute2.FixedValue = "REQUISICOESDataTable";
                type.Attributes.Add(attribute2);
                type.Particle = sequence;
                global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
                if (xs.Contains(dsSchema.TargetNamespace)) {
                    global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                    global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                    try {
                        global::System.Xml.Schema.XmlSchema schema = null;
                        dsSchema.Write(s1);
                        for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                            schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                            s2.SetLength(0);
                            schema.Write(s2);
                            if ((s1.Length == s2.Length)) {
                                s1.Position = 0;
                                s2.Position = 0;
                                for (; ((s1.Position != s1.Length) 
                                            && (s1.ReadByte() == s2.ReadByte())); ) {
                                    ;
                                }
                                if ((s1.Position == s1.Length)) {
                                    return type;
                                }
                            }
                        }
                    }
                    finally {
                        if ((s1 != null)) {
                            s1.Close();
                        }
                        if ((s2 != null)) {
                            s2.Close();
                        }
                    }
                }
                xs.Add(dsSchema);
                return type;
            }
        }
        
        /// <summary>
        ///Represents the strongly named DataTable class.
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
        [global::System.Serializable()]
        [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedTableSchema")]
        public partial class ITENS_REQUISICAODataTable : global::System.Data.DataTable, global::System.Collections.IEnumerable {
            
            private global::System.Data.DataColumn columnCOD_ITEM_REQ;
            
            private global::System.Data.DataColumn columnCOD_REQ_ITEM_REQ;
            
            private global::System.Data.DataColumn columnOP_ITEM_REQ;
            
            private global::System.Data.DataColumn columnQTDE_ITEM_REQ;
            
            private global::System.Data.DataColumn columnUNIDADE_ITEM_REQ;
            
            private global::System.Data.DataColumn columnCOD_ESTOQUE_ITEM_REQ;
            
            private global::System.Data.DataColumn columnDESCRICAO_ITEM_REQ;
            
            private global::System.Data.DataColumn columnDATA_LIMITE_ITEM_REQ;
            
            private global::System.Data.DataColumn columnURGENTE_ITEM_REQ;
            
            private global::System.Data.DataColumn columnREQUISITANTE_ITEM_REQ;
            
            private global::System.Data.DataColumn columnSETOR_ITEM_REQ;
            
            private global::System.Data.DataColumn columnDATA_REQUISICAO_ITEM_REQ;
            
            private global::System.Data.DataColumn columnSITUACAO_ATUAL_ITEM_REQ;
            
            private global::System.Data.DataColumn columnPOSICAO_ITEM_REQ;
            
            private global::System.Data.DataColumn columnCOD_FORN_ITEM_REQ;
            
            private global::System.Data.DataColumn columnITEM_ITEM_REQ;
            
            private global::System.Data.DataColumn columnAUTORIZADO_POR_ITEM_REQ;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public ITENS_REQUISICAODataTable() {
                this.TableName = "ITENS_REQUISICAO";
                this.BeginInit();
                this.InitClass();
                this.EndInit();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal ITENS_REQUISICAODataTable(global::System.Data.DataTable table) {
                this.TableName = table.TableName;
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected ITENS_REQUISICAODataTable(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                    base(info, context) {
                this.InitVars();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn COD_ITEM_REQColumn {
                get {
                    return this.columnCOD_ITEM_REQ;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn COD_REQ_ITEM_REQColumn {
                get {
                    return this.columnCOD_REQ_ITEM_REQ;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn OP_ITEM_REQColumn {
                get {
                    return this.columnOP_ITEM_REQ;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn QTDE_ITEM_REQColumn {
                get {
                    return this.columnQTDE_ITEM_REQ;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn UNIDADE_ITEM_REQColumn {
                get {
                    return this.columnUNIDADE_ITEM_REQ;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn COD_ESTOQUE_ITEM_REQColumn {
                get {
                    return this.columnCOD_ESTOQUE_ITEM_REQ;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn DESCRICAO_ITEM_REQColumn {
                get {
                    return this.columnDESCRICAO_ITEM_REQ;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn DATA_LIMITE_ITEM_REQColumn {
                get {
                    return this.columnDATA_LIMITE_ITEM_REQ;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn URGENTE_ITEM_REQColumn {
                get {
                    return this.columnURGENTE_ITEM_REQ;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn REQUISITANTE_ITEM_REQColumn {
                get {
                    return this.columnREQUISITANTE_ITEM_REQ;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn SETOR_ITEM_REQColumn {
                get {
                    return this.columnSETOR_ITEM_REQ;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn DATA_REQUISICAO_ITEM_REQColumn {
                get {
                    return this.columnDATA_REQUISICAO_ITEM_REQ;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn SITUACAO_ATUAL_ITEM_REQColumn {
                get {
                    return this.columnSITUACAO_ATUAL_ITEM_REQ;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn POSICAO_ITEM_REQColumn {
                get {
                    return this.columnPOSICAO_ITEM_REQ;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn COD_FORN_ITEM_REQColumn {
                get {
                    return this.columnCOD_FORN_ITEM_REQ;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn ITEM_ITEM_REQColumn {
                get {
                    return this.columnITEM_ITEM_REQ;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn AUTORIZADO_POR_ITEM_REQColumn {
                get {
                    return this.columnAUTORIZADO_POR_ITEM_REQ;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public ITENS_REQUISICAORow this[int index] {
                get {
                    return ((ITENS_REQUISICAORow)(this.Rows[index]));
                }
            }
            
            public event ITENS_REQUISICAORowChangeEventHandler ITENS_REQUISICAORowChanging;
            
            public event ITENS_REQUISICAORowChangeEventHandler ITENS_REQUISICAORowChanged;
            
            public event ITENS_REQUISICAORowChangeEventHandler ITENS_REQUISICAORowDeleting;
            
            public event ITENS_REQUISICAORowChangeEventHandler ITENS_REQUISICAORowDeleted;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void AddITENS_REQUISICAORow(ITENS_REQUISICAORow row) {
                this.Rows.Add(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public ITENS_REQUISICAORow AddITENS_REQUISICAORow(
                        int COD_ITEM_REQ, 
                        int COD_REQ_ITEM_REQ, 
                        string OP_ITEM_REQ, 
                        double QTDE_ITEM_REQ, 
                        string UNIDADE_ITEM_REQ, 
                        int COD_ESTOQUE_ITEM_REQ, 
                        string DESCRICAO_ITEM_REQ, 
                        System.DateTime DATA_LIMITE_ITEM_REQ, 
                        int URGENTE_ITEM_REQ, 
                        string REQUISITANTE_ITEM_REQ, 
                        string SETOR_ITEM_REQ, 
                        System.DateTime DATA_REQUISICAO_ITEM_REQ, 
                        string SITUACAO_ATUAL_ITEM_REQ, 
                        string POSICAO_ITEM_REQ, 
                        string COD_FORN_ITEM_REQ, 
                        string ITEM_ITEM_REQ, 
                        string AUTORIZADO_POR_ITEM_REQ) {
                ITENS_REQUISICAORow rowITENS_REQUISICAORow = ((ITENS_REQUISICAORow)(this.NewRow()));
                object[] columnValuesArray = new object[] {
                        COD_ITEM_REQ,
                        COD_REQ_ITEM_REQ,
                        OP_ITEM_REQ,
                        QTDE_ITEM_REQ,
                        UNIDADE_ITEM_REQ,
                        COD_ESTOQUE_ITEM_REQ,
                        DESCRICAO_ITEM_REQ,
                        DATA_LIMITE_ITEM_REQ,
                        URGENTE_ITEM_REQ,
                        REQUISITANTE_ITEM_REQ,
                        SETOR_ITEM_REQ,
                        DATA_REQUISICAO_ITEM_REQ,
                        SITUACAO_ATUAL_ITEM_REQ,
                        POSICAO_ITEM_REQ,
                        COD_FORN_ITEM_REQ,
                        ITEM_ITEM_REQ,
                        AUTORIZADO_POR_ITEM_REQ};
                rowITENS_REQUISICAORow.ItemArray = columnValuesArray;
                this.Rows.Add(rowITENS_REQUISICAORow);
                return rowITENS_REQUISICAORow;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public ITENS_REQUISICAORow FindByCOD_ITEM_REQ(int COD_ITEM_REQ) {
                return ((ITENS_REQUISICAORow)(this.Rows.Find(new object[] {
                            COD_ITEM_REQ})));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public virtual global::System.Collections.IEnumerator GetEnumerator() {
                return this.Rows.GetEnumerator();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public override global::System.Data.DataTable Clone() {
                ITENS_REQUISICAODataTable cln = ((ITENS_REQUISICAODataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override global::System.Data.DataTable CreateInstance() {
                return new ITENS_REQUISICAODataTable();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal void InitVars() {
                this.columnCOD_ITEM_REQ = base.Columns["COD_ITEM_REQ"];
                this.columnCOD_REQ_ITEM_REQ = base.Columns["COD_REQ_ITEM_REQ"];
                this.columnOP_ITEM_REQ = base.Columns["OP_ITEM_REQ"];
                this.columnQTDE_ITEM_REQ = base.Columns["QTDE_ITEM_REQ"];
                this.columnUNIDADE_ITEM_REQ = base.Columns["UNIDADE_ITEM_REQ"];
                this.columnCOD_ESTOQUE_ITEM_REQ = base.Columns["COD_ESTOQUE_ITEM_REQ"];
                this.columnDESCRICAO_ITEM_REQ = base.Columns["DESCRICAO_ITEM_REQ"];
                this.columnDATA_LIMITE_ITEM_REQ = base.Columns["DATA_LIMITE_ITEM_REQ"];
                this.columnURGENTE_ITEM_REQ = base.Columns["URGENTE_ITEM_REQ"];
                this.columnREQUISITANTE_ITEM_REQ = base.Columns["REQUISITANTE_ITEM_REQ"];
                this.columnSETOR_ITEM_REQ = base.Columns["SETOR_ITEM_REQ"];
                this.columnDATA_REQUISICAO_ITEM_REQ = base.Columns["DATA_REQUISICAO_ITEM_REQ"];
                this.columnSITUACAO_ATUAL_ITEM_REQ = base.Columns["SITUACAO_ATUAL_ITEM_REQ"];
                this.columnPOSICAO_ITEM_REQ = base.Columns["POSICAO_ITEM_REQ"];
                this.columnCOD_FORN_ITEM_REQ = base.Columns["COD_FORN_ITEM_REQ"];
                this.columnITEM_ITEM_REQ = base.Columns["ITEM_ITEM_REQ"];
                this.columnAUTORIZADO_POR_ITEM_REQ = base.Columns["AUTORIZADO_POR_ITEM_REQ"];
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            private void InitClass() {
                this.columnCOD_ITEM_REQ = new global::System.Data.DataColumn("COD_ITEM_REQ", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnCOD_ITEM_REQ);
                this.columnCOD_REQ_ITEM_REQ = new global::System.Data.DataColumn("COD_REQ_ITEM_REQ", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnCOD_REQ_ITEM_REQ);
                this.columnOP_ITEM_REQ = new global::System.Data.DataColumn("OP_ITEM_REQ", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnOP_ITEM_REQ);
                this.columnQTDE_ITEM_REQ = new global::System.Data.DataColumn("QTDE_ITEM_REQ", typeof(double), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnQTDE_ITEM_REQ);
                this.columnUNIDADE_ITEM_REQ = new global::System.Data.DataColumn("UNIDADE_ITEM_REQ", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnUNIDADE_ITEM_REQ);
                this.columnCOD_ESTOQUE_ITEM_REQ = new global::System.Data.DataColumn("COD_ESTOQUE_ITEM_REQ", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnCOD_ESTOQUE_ITEM_REQ);
                this.columnDESCRICAO_ITEM_REQ = new global::System.Data.DataColumn("DESCRICAO_ITEM_REQ", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnDESCRICAO_ITEM_REQ);
                this.columnDATA_LIMITE_ITEM_REQ = new global::System.Data.DataColumn("DATA_LIMITE_ITEM_REQ", typeof(global::System.DateTime), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnDATA_LIMITE_ITEM_REQ);
                this.columnURGENTE_ITEM_REQ = new global::System.Data.DataColumn("URGENTE_ITEM_REQ", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnURGENTE_ITEM_REQ);
                this.columnREQUISITANTE_ITEM_REQ = new global::System.Data.DataColumn("REQUISITANTE_ITEM_REQ", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnREQUISITANTE_ITEM_REQ);
                this.columnSETOR_ITEM_REQ = new global::System.Data.DataColumn("SETOR_ITEM_REQ", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnSETOR_ITEM_REQ);
                this.columnDATA_REQUISICAO_ITEM_REQ = new global::System.Data.DataColumn("DATA_REQUISICAO_ITEM_REQ", typeof(global::System.DateTime), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnDATA_REQUISICAO_ITEM_REQ);
                this.columnSITUACAO_ATUAL_ITEM_REQ = new global::System.Data.DataColumn("SITUACAO_ATUAL_ITEM_REQ", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnSITUACAO_ATUAL_ITEM_REQ);
                this.columnPOSICAO_ITEM_REQ = new global::System.Data.DataColumn("POSICAO_ITEM_REQ", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnPOSICAO_ITEM_REQ);
                this.columnCOD_FORN_ITEM_REQ = new global::System.Data.DataColumn("COD_FORN_ITEM_REQ", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnCOD_FORN_ITEM_REQ);
                this.columnITEM_ITEM_REQ = new global::System.Data.DataColumn("ITEM_ITEM_REQ", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnITEM_ITEM_REQ);
                this.columnAUTORIZADO_POR_ITEM_REQ = new global::System.Data.DataColumn("AUTORIZADO_POR_ITEM_REQ", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnAUTORIZADO_POR_ITEM_REQ);
                this.Constraints.Add(new global::System.Data.UniqueConstraint("Constraint1", new global::System.Data.DataColumn[] {
                                this.columnCOD_ITEM_REQ}, true));
                this.columnCOD_ITEM_REQ.AllowDBNull = false;
                this.columnCOD_ITEM_REQ.Unique = true;
                this.columnOP_ITEM_REQ.MaxLength = 50;
                this.columnUNIDADE_ITEM_REQ.MaxLength = 10;
                this.columnDESCRICAO_ITEM_REQ.MaxLength = 200;
                this.columnREQUISITANTE_ITEM_REQ.MaxLength = 100;
                this.columnSETOR_ITEM_REQ.MaxLength = 100;
                this.columnSITUACAO_ATUAL_ITEM_REQ.MaxLength = 50;
                this.columnPOSICAO_ITEM_REQ.MaxLength = 50;
                this.columnCOD_FORN_ITEM_REQ.MaxLength = 200;
                this.columnITEM_ITEM_REQ.MaxLength = 200;
                this.columnAUTORIZADO_POR_ITEM_REQ.MaxLength = 50;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public ITENS_REQUISICAORow NewITENS_REQUISICAORow() {
                return ((ITENS_REQUISICAORow)(this.NewRow()));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override global::System.Data.DataRow NewRowFromBuilder(global::System.Data.DataRowBuilder builder) {
                return new ITENS_REQUISICAORow(builder);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override global::System.Type GetRowType() {
                return typeof(ITENS_REQUISICAORow);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowChanged(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.ITENS_REQUISICAORowChanged != null)) {
                    this.ITENS_REQUISICAORowChanged(this, new ITENS_REQUISICAORowChangeEvent(((ITENS_REQUISICAORow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowChanging(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.ITENS_REQUISICAORowChanging != null)) {
                    this.ITENS_REQUISICAORowChanging(this, new ITENS_REQUISICAORowChangeEvent(((ITENS_REQUISICAORow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowDeleted(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.ITENS_REQUISICAORowDeleted != null)) {
                    this.ITENS_REQUISICAORowDeleted(this, new ITENS_REQUISICAORowChangeEvent(((ITENS_REQUISICAORow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowDeleting(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.ITENS_REQUISICAORowDeleting != null)) {
                    this.ITENS_REQUISICAORowDeleting(this, new ITENS_REQUISICAORowChangeEvent(((ITENS_REQUISICAORow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void RemoveITENS_REQUISICAORow(ITENS_REQUISICAORow row) {
                this.Rows.Remove(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedTableSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
                global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
                global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
                dsRequisicao ds = new dsRequisicao();
                global::System.Xml.Schema.XmlSchemaAny any1 = new global::System.Xml.Schema.XmlSchemaAny();
                any1.Namespace = "http://www.w3.org/2001/XMLSchema";
                any1.MinOccurs = new decimal(0);
                any1.MaxOccurs = decimal.MaxValue;
                any1.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any1);
                global::System.Xml.Schema.XmlSchemaAny any2 = new global::System.Xml.Schema.XmlSchemaAny();
                any2.Namespace = "urn:schemas-microsoft-com:xml-diffgram-v1";
                any2.MinOccurs = new decimal(1);
                any2.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any2);
                global::System.Xml.Schema.XmlSchemaAttribute attribute1 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute1.Name = "namespace";
                attribute1.FixedValue = ds.Namespace;
                type.Attributes.Add(attribute1);
                global::System.Xml.Schema.XmlSchemaAttribute attribute2 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute2.Name = "tableTypeName";
                attribute2.FixedValue = "ITENS_REQUISICAODataTable";
                type.Attributes.Add(attribute2);
                type.Particle = sequence;
                global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
                if (xs.Contains(dsSchema.TargetNamespace)) {
                    global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                    global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                    try {
                        global::System.Xml.Schema.XmlSchema schema = null;
                        dsSchema.Write(s1);
                        for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                            schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                            s2.SetLength(0);
                            schema.Write(s2);
                            if ((s1.Length == s2.Length)) {
                                s1.Position = 0;
                                s2.Position = 0;
                                for (; ((s1.Position != s1.Length) 
                                            && (s1.ReadByte() == s2.ReadByte())); ) {
                                    ;
                                }
                                if ((s1.Position == s1.Length)) {
                                    return type;
                                }
                            }
                        }
                    }
                    finally {
                        if ((s1 != null)) {
                            s1.Close();
                        }
                        if ((s2 != null)) {
                            s2.Close();
                        }
                    }
                }
                xs.Add(dsSchema);
                return type;
            }
        }
        
        /// <summary>
        ///Represents strongly named DataRow class.
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
        public partial class REQUISICOESRow : global::System.Data.DataRow {
            
            private REQUISICOESDataTable tableREQUISICOES;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal REQUISICOESRow(global::System.Data.DataRowBuilder rb) : 
                    base(rb) {
                this.tableREQUISICOES = ((REQUISICOESDataTable)(this.Table));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public int COD_REQUISICAO {
                get {
                    return ((int)(this[this.tableREQUISICOES.COD_REQUISICAOColumn]));
                }
                set {
                    this[this.tableREQUISICOES.COD_REQUISICAOColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string REQUISITANTE_REQUISICAO {
                get {
                    try {
                        return ((string)(this[this.tableREQUISICOES.REQUISITANTE_REQUISICAOColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'REQUISITANTE_REQUISICAO\' in table \'REQUISICOES\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableREQUISICOES.REQUISITANTE_REQUISICAOColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string SETOR_REQUISICAO {
                get {
                    try {
                        return ((string)(this[this.tableREQUISICOES.SETOR_REQUISICAOColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'SETOR_REQUISICAO\' in table \'REQUISICOES\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableREQUISICOES.SETOR_REQUISICAOColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string OBS_REQUISICAO {
                get {
                    try {
                        return ((string)(this[this.tableREQUISICOES.OBS_REQUISICAOColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'OBS_REQUISICAO\' in table \'REQUISICOES\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableREQUISICOES.OBS_REQUISICAOColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.DateTime DATA_REQUISICAO {
                get {
                    try {
                        return ((global::System.DateTime)(this[this.tableREQUISICOES.DATA_REQUISICAOColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'DATA_REQUISICAO\' in table \'REQUISICOES\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableREQUISICOES.DATA_REQUISICAOColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsREQUISITANTE_REQUISICAONull() {
                return this.IsNull(this.tableREQUISICOES.REQUISITANTE_REQUISICAOColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetREQUISITANTE_REQUISICAONull() {
                this[this.tableREQUISICOES.REQUISITANTE_REQUISICAOColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsSETOR_REQUISICAONull() {
                return this.IsNull(this.tableREQUISICOES.SETOR_REQUISICAOColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetSETOR_REQUISICAONull() {
                this[this.tableREQUISICOES.SETOR_REQUISICAOColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsOBS_REQUISICAONull() {
                return this.IsNull(this.tableREQUISICOES.OBS_REQUISICAOColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetOBS_REQUISICAONull() {
                this[this.tableREQUISICOES.OBS_REQUISICAOColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsDATA_REQUISICAONull() {
                return this.IsNull(this.tableREQUISICOES.DATA_REQUISICAOColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetDATA_REQUISICAONull() {
                this[this.tableREQUISICOES.DATA_REQUISICAOColumn] = global::System.Convert.DBNull;
            }
        }
        
        /// <summary>
        ///Represents strongly named DataRow class.
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
        public partial class ITENS_REQUISICAORow : global::System.Data.DataRow {
            
            private ITENS_REQUISICAODataTable tableITENS_REQUISICAO;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal ITENS_REQUISICAORow(global::System.Data.DataRowBuilder rb) : 
                    base(rb) {
                this.tableITENS_REQUISICAO = ((ITENS_REQUISICAODataTable)(this.Table));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public int COD_ITEM_REQ {
                get {
                    return ((int)(this[this.tableITENS_REQUISICAO.COD_ITEM_REQColumn]));
                }
                set {
                    this[this.tableITENS_REQUISICAO.COD_ITEM_REQColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public int COD_REQ_ITEM_REQ {
                get {
                    try {
                        return ((int)(this[this.tableITENS_REQUISICAO.COD_REQ_ITEM_REQColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'COD_REQ_ITEM_REQ\' in table \'ITENS_REQUISICAO\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableITENS_REQUISICAO.COD_REQ_ITEM_REQColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string OP_ITEM_REQ {
                get {
                    try {
                        return ((string)(this[this.tableITENS_REQUISICAO.OP_ITEM_REQColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'OP_ITEM_REQ\' in table \'ITENS_REQUISICAO\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableITENS_REQUISICAO.OP_ITEM_REQColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public double QTDE_ITEM_REQ {
                get {
                    try {
                        return ((double)(this[this.tableITENS_REQUISICAO.QTDE_ITEM_REQColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'QTDE_ITEM_REQ\' in table \'ITENS_REQUISICAO\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableITENS_REQUISICAO.QTDE_ITEM_REQColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string UNIDADE_ITEM_REQ {
                get {
                    try {
                        return ((string)(this[this.tableITENS_REQUISICAO.UNIDADE_ITEM_REQColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'UNIDADE_ITEM_REQ\' in table \'ITENS_REQUISICAO\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableITENS_REQUISICAO.UNIDADE_ITEM_REQColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public int COD_ESTOQUE_ITEM_REQ {
                get {
                    try {
                        return ((int)(this[this.tableITENS_REQUISICAO.COD_ESTOQUE_ITEM_REQColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'COD_ESTOQUE_ITEM_REQ\' in table \'ITENS_REQUISICAO\' is DBNull" +
                                ".", e);
                    }
                }
                set {
                    this[this.tableITENS_REQUISICAO.COD_ESTOQUE_ITEM_REQColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string DESCRICAO_ITEM_REQ {
                get {
                    try {
                        return ((string)(this[this.tableITENS_REQUISICAO.DESCRICAO_ITEM_REQColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'DESCRICAO_ITEM_REQ\' in table \'ITENS_REQUISICAO\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableITENS_REQUISICAO.DESCRICAO_ITEM_REQColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.DateTime DATA_LIMITE_ITEM_REQ {
                get {
                    try {
                        return ((global::System.DateTime)(this[this.tableITENS_REQUISICAO.DATA_LIMITE_ITEM_REQColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'DATA_LIMITE_ITEM_REQ\' in table \'ITENS_REQUISICAO\' is DBNull" +
                                ".", e);
                    }
                }
                set {
                    this[this.tableITENS_REQUISICAO.DATA_LIMITE_ITEM_REQColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public int URGENTE_ITEM_REQ {
                get {
                    try {
                        return ((int)(this[this.tableITENS_REQUISICAO.URGENTE_ITEM_REQColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'URGENTE_ITEM_REQ\' in table \'ITENS_REQUISICAO\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableITENS_REQUISICAO.URGENTE_ITEM_REQColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string REQUISITANTE_ITEM_REQ {
                get {
                    try {
                        return ((string)(this[this.tableITENS_REQUISICAO.REQUISITANTE_ITEM_REQColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'REQUISITANTE_ITEM_REQ\' in table \'ITENS_REQUISICAO\' is DBNul" +
                                "l.", e);
                    }
                }
                set {
                    this[this.tableITENS_REQUISICAO.REQUISITANTE_ITEM_REQColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string SETOR_ITEM_REQ {
                get {
                    try {
                        return ((string)(this[this.tableITENS_REQUISICAO.SETOR_ITEM_REQColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'SETOR_ITEM_REQ\' in table \'ITENS_REQUISICAO\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableITENS_REQUISICAO.SETOR_ITEM_REQColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.DateTime DATA_REQUISICAO_ITEM_REQ {
                get {
                    try {
                        return ((global::System.DateTime)(this[this.tableITENS_REQUISICAO.DATA_REQUISICAO_ITEM_REQColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'DATA_REQUISICAO_ITEM_REQ\' in table \'ITENS_REQUISICAO\' is DB" +
                                "Null.", e);
                    }
                }
                set {
                    this[this.tableITENS_REQUISICAO.DATA_REQUISICAO_ITEM_REQColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string SITUACAO_ATUAL_ITEM_REQ {
                get {
                    try {
                        return ((string)(this[this.tableITENS_REQUISICAO.SITUACAO_ATUAL_ITEM_REQColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'SITUACAO_ATUAL_ITEM_REQ\' in table \'ITENS_REQUISICAO\' is DBN" +
                                "ull.", e);
                    }
                }
                set {
                    this[this.tableITENS_REQUISICAO.SITUACAO_ATUAL_ITEM_REQColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string POSICAO_ITEM_REQ {
                get {
                    try {
                        return ((string)(this[this.tableITENS_REQUISICAO.POSICAO_ITEM_REQColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'POSICAO_ITEM_REQ\' in table \'ITENS_REQUISICAO\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableITENS_REQUISICAO.POSICAO_ITEM_REQColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string COD_FORN_ITEM_REQ {
                get {
                    try {
                        return ((string)(this[this.tableITENS_REQUISICAO.COD_FORN_ITEM_REQColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'COD_FORN_ITEM_REQ\' in table \'ITENS_REQUISICAO\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableITENS_REQUISICAO.COD_FORN_ITEM_REQColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string ITEM_ITEM_REQ {
                get {
                    try {
                        return ((string)(this[this.tableITENS_REQUISICAO.ITEM_ITEM_REQColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'ITEM_ITEM_REQ\' in table \'ITENS_REQUISICAO\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableITENS_REQUISICAO.ITEM_ITEM_REQColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string AUTORIZADO_POR_ITEM_REQ {
                get {
                    try {
                        return ((string)(this[this.tableITENS_REQUISICAO.AUTORIZADO_POR_ITEM_REQColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'AUTORIZADO_POR_ITEM_REQ\' in table \'ITENS_REQUISICAO\' is DBN" +
                                "ull.", e);
                    }
                }
                set {
                    this[this.tableITENS_REQUISICAO.AUTORIZADO_POR_ITEM_REQColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsCOD_REQ_ITEM_REQNull() {
                return this.IsNull(this.tableITENS_REQUISICAO.COD_REQ_ITEM_REQColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetCOD_REQ_ITEM_REQNull() {
                this[this.tableITENS_REQUISICAO.COD_REQ_ITEM_REQColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsOP_ITEM_REQNull() {
                return this.IsNull(this.tableITENS_REQUISICAO.OP_ITEM_REQColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetOP_ITEM_REQNull() {
                this[this.tableITENS_REQUISICAO.OP_ITEM_REQColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsQTDE_ITEM_REQNull() {
                return this.IsNull(this.tableITENS_REQUISICAO.QTDE_ITEM_REQColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetQTDE_ITEM_REQNull() {
                this[this.tableITENS_REQUISICAO.QTDE_ITEM_REQColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsUNIDADE_ITEM_REQNull() {
                return this.IsNull(this.tableITENS_REQUISICAO.UNIDADE_ITEM_REQColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetUNIDADE_ITEM_REQNull() {
                this[this.tableITENS_REQUISICAO.UNIDADE_ITEM_REQColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsCOD_ESTOQUE_ITEM_REQNull() {
                return this.IsNull(this.tableITENS_REQUISICAO.COD_ESTOQUE_ITEM_REQColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetCOD_ESTOQUE_ITEM_REQNull() {
                this[this.tableITENS_REQUISICAO.COD_ESTOQUE_ITEM_REQColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsDESCRICAO_ITEM_REQNull() {
                return this.IsNull(this.tableITENS_REQUISICAO.DESCRICAO_ITEM_REQColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetDESCRICAO_ITEM_REQNull() {
                this[this.tableITENS_REQUISICAO.DESCRICAO_ITEM_REQColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsDATA_LIMITE_ITEM_REQNull() {
                return this.IsNull(this.tableITENS_REQUISICAO.DATA_LIMITE_ITEM_REQColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetDATA_LIMITE_ITEM_REQNull() {
                this[this.tableITENS_REQUISICAO.DATA_LIMITE_ITEM_REQColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsURGENTE_ITEM_REQNull() {
                return this.IsNull(this.tableITENS_REQUISICAO.URGENTE_ITEM_REQColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetURGENTE_ITEM_REQNull() {
                this[this.tableITENS_REQUISICAO.URGENTE_ITEM_REQColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsREQUISITANTE_ITEM_REQNull() {
                return this.IsNull(this.tableITENS_REQUISICAO.REQUISITANTE_ITEM_REQColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetREQUISITANTE_ITEM_REQNull() {
                this[this.tableITENS_REQUISICAO.REQUISITANTE_ITEM_REQColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsSETOR_ITEM_REQNull() {
                return this.IsNull(this.tableITENS_REQUISICAO.SETOR_ITEM_REQColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetSETOR_ITEM_REQNull() {
                this[this.tableITENS_REQUISICAO.SETOR_ITEM_REQColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsDATA_REQUISICAO_ITEM_REQNull() {
                return this.IsNull(this.tableITENS_REQUISICAO.DATA_REQUISICAO_ITEM_REQColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetDATA_REQUISICAO_ITEM_REQNull() {
                this[this.tableITENS_REQUISICAO.DATA_REQUISICAO_ITEM_REQColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsSITUACAO_ATUAL_ITEM_REQNull() {
                return this.IsNull(this.tableITENS_REQUISICAO.SITUACAO_ATUAL_ITEM_REQColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetSITUACAO_ATUAL_ITEM_REQNull() {
                this[this.tableITENS_REQUISICAO.SITUACAO_ATUAL_ITEM_REQColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsPOSICAO_ITEM_REQNull() {
                return this.IsNull(this.tableITENS_REQUISICAO.POSICAO_ITEM_REQColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetPOSICAO_ITEM_REQNull() {
                this[this.tableITENS_REQUISICAO.POSICAO_ITEM_REQColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsCOD_FORN_ITEM_REQNull() {
                return this.IsNull(this.tableITENS_REQUISICAO.COD_FORN_ITEM_REQColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetCOD_FORN_ITEM_REQNull() {
                this[this.tableITENS_REQUISICAO.COD_FORN_ITEM_REQColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsITEM_ITEM_REQNull() {
                return this.IsNull(this.tableITENS_REQUISICAO.ITEM_ITEM_REQColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetITEM_ITEM_REQNull() {
                this[this.tableITENS_REQUISICAO.ITEM_ITEM_REQColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsAUTORIZADO_POR_ITEM_REQNull() {
                return this.IsNull(this.tableITENS_REQUISICAO.AUTORIZADO_POR_ITEM_REQColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetAUTORIZADO_POR_ITEM_REQNull() {
                this[this.tableITENS_REQUISICAO.AUTORIZADO_POR_ITEM_REQColumn] = global::System.Convert.DBNull;
            }
        }
        
        /// <summary>
        ///Row event argument class
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
        public class REQUISICOESRowChangeEvent : global::System.EventArgs {
            
            private REQUISICOESRow eventRow;
            
            private global::System.Data.DataRowAction eventAction;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public REQUISICOESRowChangeEvent(REQUISICOESRow row, global::System.Data.DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public REQUISICOESRow Row {
                get {
                    return this.eventRow;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
        
        /// <summary>
        ///Row event argument class
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
        public class ITENS_REQUISICAORowChangeEvent : global::System.EventArgs {
            
            private ITENS_REQUISICAORow eventRow;
            
            private global::System.Data.DataRowAction eventAction;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public ITENS_REQUISICAORowChangeEvent(ITENS_REQUISICAORow row, global::System.Data.DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public ITENS_REQUISICAORow Row {
                get {
                    return this.eventRow;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
    }
}
namespace Evolucao.dsRequisicaoTableAdapters {
    
    
    /// <summary>
    ///Represents the connection and commands used to retrieve and save data.
    ///</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
    [global::System.ComponentModel.DesignerCategoryAttribute("code")]
    [global::System.ComponentModel.ToolboxItem(true)]
    [global::System.ComponentModel.DataObjectAttribute(true)]
    [global::System.ComponentModel.DesignerAttribute("Microsoft.VSDesigner.DataSource.Design.TableAdapterDesigner, Microsoft.VSDesigner" +
        ", Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a")]
    [global::System.ComponentModel.Design.HelpKeywordAttribute("vs.data.TableAdapter")]
    public partial class REQUISICOESTableAdapter : global::System.ComponentModel.Component {
        
        private global::System.Data.Odbc.OdbcDataAdapter _adapter;
        
        private global::System.Data.Odbc.OdbcConnection _connection;
        
        private global::System.Data.Odbc.OdbcCommand[] _commandCollection;
        
        private bool _clearBeforeFill;
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public REQUISICOESTableAdapter() {
            this.ClearBeforeFill = true;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Data.Odbc.OdbcDataAdapter Adapter {
            get {
                if ((this._adapter == null)) {
                    this.InitAdapter();
                }
                return this._adapter;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        internal global::System.Data.Odbc.OdbcConnection Connection {
            get {
                if ((this._connection == null)) {
                    this.InitConnection();
                }
                return this._connection;
            }
            set {
                this._connection = value;
                if ((this.Adapter.InsertCommand != null)) {
                    this.Adapter.InsertCommand.Connection = value;
                }
                if ((this.Adapter.DeleteCommand != null)) {
                    this.Adapter.DeleteCommand.Connection = value;
                }
                if ((this.Adapter.UpdateCommand != null)) {
                    this.Adapter.UpdateCommand.Connection = value;
                }
                for (int i = 0; (i < this.CommandCollection.Length); i = (i + 1)) {
                    if ((this.CommandCollection[i] != null)) {
                        ((global::System.Data.Odbc.OdbcCommand)(this.CommandCollection[i])).Connection = value;
                    }
                }
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected global::System.Data.Odbc.OdbcCommand[] CommandCollection {
            get {
                if ((this._commandCollection == null)) {
                    this.InitCommandCollection();
                }
                return this._commandCollection;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public bool ClearBeforeFill {
            get {
                return this._clearBeforeFill;
            }
            set {
                this._clearBeforeFill = value;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void InitAdapter() {
            this._adapter = new global::System.Data.Odbc.OdbcDataAdapter();
            global::System.Data.Common.DataTableMapping tableMapping = new global::System.Data.Common.DataTableMapping();
            tableMapping.SourceTable = "Table";
            tableMapping.DataSetTable = "REQUISICOES";
            tableMapping.ColumnMappings.Add("COD_REQUISICAO", "COD_REQUISICAO");
            tableMapping.ColumnMappings.Add("REQUISITANTE_REQUISICAO", "REQUISITANTE_REQUISICAO");
            tableMapping.ColumnMappings.Add("SETOR_REQUISICAO", "SETOR_REQUISICAO");
            tableMapping.ColumnMappings.Add("OBS_REQUISICAO", "OBS_REQUISICAO");
            tableMapping.ColumnMappings.Add("DATA_REQUISICAO", "DATA_REQUISICAO");
            this._adapter.TableMappings.Add(tableMapping);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void InitConnection() {
            this._connection = new global::System.Data.Odbc.OdbcConnection();
            this._connection.ConnectionString = global::Evolucao.Properties.Settings.Default.connection_firebird;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void InitCommandCollection() {
            this._commandCollection = new global::System.Data.Odbc.OdbcCommand[1];
            this._commandCollection[0] = new global::System.Data.Odbc.OdbcCommand();
            this._commandCollection[0].Connection = this.Connection;
            this._commandCollection[0].CommandText = "select * from requisicoes";
            this._commandCollection[0].CommandType = global::System.Data.CommandType.Text;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.Design.HelpKeywordAttribute("vs.data.TableAdapter")]
        [global::System.ComponentModel.DataObjectMethodAttribute(global::System.ComponentModel.DataObjectMethodType.Fill, true)]
        public virtual int Fill(dsRequisicao.REQUISICOESDataTable dataTable) {
            this.Adapter.SelectCommand = this.CommandCollection[0];
            if ((this.ClearBeforeFill == true)) {
                dataTable.Clear();
            }
            int returnValue = this.Adapter.Fill(dataTable);
            return returnValue;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.Design.HelpKeywordAttribute("vs.data.TableAdapter")]
        [global::System.ComponentModel.DataObjectMethodAttribute(global::System.ComponentModel.DataObjectMethodType.Select, true)]
        public virtual dsRequisicao.REQUISICOESDataTable GetData() {
            this.Adapter.SelectCommand = this.CommandCollection[0];
            dsRequisicao.REQUISICOESDataTable dataTable = new dsRequisicao.REQUISICOESDataTable();
            this.Adapter.Fill(dataTable);
            return dataTable;
        }
    }
    
    /// <summary>
    ///Represents the connection and commands used to retrieve and save data.
    ///</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
    [global::System.ComponentModel.DesignerCategoryAttribute("code")]
    [global::System.ComponentModel.ToolboxItem(true)]
    [global::System.ComponentModel.DataObjectAttribute(true)]
    [global::System.ComponentModel.DesignerAttribute("Microsoft.VSDesigner.DataSource.Design.TableAdapterDesigner, Microsoft.VSDesigner" +
        ", Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a")]
    [global::System.ComponentModel.Design.HelpKeywordAttribute("vs.data.TableAdapter")]
    public partial class ITENS_REQUISICAOTableAdapter : global::System.ComponentModel.Component {
        
        private global::System.Data.Odbc.OdbcDataAdapter _adapter;
        
        private global::System.Data.Odbc.OdbcConnection _connection;
        
        private global::System.Data.Odbc.OdbcCommand[] _commandCollection;
        
        private bool _clearBeforeFill;
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public ITENS_REQUISICAOTableAdapter() {
            this.ClearBeforeFill = true;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Data.Odbc.OdbcDataAdapter Adapter {
            get {
                if ((this._adapter == null)) {
                    this.InitAdapter();
                }
                return this._adapter;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        internal global::System.Data.Odbc.OdbcConnection Connection {
            get {
                if ((this._connection == null)) {
                    this.InitConnection();
                }
                return this._connection;
            }
            set {
                this._connection = value;
                if ((this.Adapter.InsertCommand != null)) {
                    this.Adapter.InsertCommand.Connection = value;
                }
                if ((this.Adapter.DeleteCommand != null)) {
                    this.Adapter.DeleteCommand.Connection = value;
                }
                if ((this.Adapter.UpdateCommand != null)) {
                    this.Adapter.UpdateCommand.Connection = value;
                }
                for (int i = 0; (i < this.CommandCollection.Length); i = (i + 1)) {
                    if ((this.CommandCollection[i] != null)) {
                        ((global::System.Data.Odbc.OdbcCommand)(this.CommandCollection[i])).Connection = value;
                    }
                }
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected global::System.Data.Odbc.OdbcCommand[] CommandCollection {
            get {
                if ((this._commandCollection == null)) {
                    this.InitCommandCollection();
                }
                return this._commandCollection;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public bool ClearBeforeFill {
            get {
                return this._clearBeforeFill;
            }
            set {
                this._clearBeforeFill = value;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void InitAdapter() {
            this._adapter = new global::System.Data.Odbc.OdbcDataAdapter();
            global::System.Data.Common.DataTableMapping tableMapping = new global::System.Data.Common.DataTableMapping();
            tableMapping.SourceTable = "Table";
            tableMapping.DataSetTable = "ITENS_REQUISICAO";
            tableMapping.ColumnMappings.Add("COD_ITEM_REQ", "COD_ITEM_REQ");
            tableMapping.ColumnMappings.Add("COD_REQ_ITEM_REQ", "COD_REQ_ITEM_REQ");
            tableMapping.ColumnMappings.Add("OP_ITEM_REQ", "OP_ITEM_REQ");
            tableMapping.ColumnMappings.Add("QTDE_ITEM_REQ", "QTDE_ITEM_REQ");
            tableMapping.ColumnMappings.Add("UNIDADE_ITEM_REQ", "UNIDADE_ITEM_REQ");
            tableMapping.ColumnMappings.Add("COD_ESTOQUE_ITEM_REQ", "COD_ESTOQUE_ITEM_REQ");
            tableMapping.ColumnMappings.Add("DESCRICAO_ITEM_REQ", "DESCRICAO_ITEM_REQ");
            tableMapping.ColumnMappings.Add("DATA_LIMITE_ITEM_REQ", "DATA_LIMITE_ITEM_REQ");
            tableMapping.ColumnMappings.Add("URGENTE_ITEM_REQ", "URGENTE_ITEM_REQ");
            tableMapping.ColumnMappings.Add("REQUISITANTE_ITEM_REQ", "REQUISITANTE_ITEM_REQ");
            tableMapping.ColumnMappings.Add("SETOR_ITEM_REQ", "SETOR_ITEM_REQ");
            tableMapping.ColumnMappings.Add("DATA_REQUISICAO_ITEM_REQ", "DATA_REQUISICAO_ITEM_REQ");
            tableMapping.ColumnMappings.Add("SITUACAO_ATUAL_ITEM_REQ", "SITUACAO_ATUAL_ITEM_REQ");
            this._adapter.TableMappings.Add(tableMapping);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void InitConnection() {
            this._connection = new global::System.Data.Odbc.OdbcConnection();
            this._connection.ConnectionString = global::Evolucao.Properties.Settings.Default.connection_firebird;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void InitCommandCollection() {
            this._commandCollection = new global::System.Data.Odbc.OdbcCommand[1];
            this._commandCollection[0] = new global::System.Data.Odbc.OdbcCommand();
            this._commandCollection[0].Connection = this.Connection;
            this._commandCollection[0].CommandText = "SELECT * FROM ITENS_REQUISICAO";
            this._commandCollection[0].CommandType = global::System.Data.CommandType.Text;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.Design.HelpKeywordAttribute("vs.data.TableAdapter")]
        [global::System.ComponentModel.DataObjectMethodAttribute(global::System.ComponentModel.DataObjectMethodType.Fill, true)]
        public virtual int Fill(dsRequisicao.ITENS_REQUISICAODataTable dataTable) {
            this.Adapter.SelectCommand = this.CommandCollection[0];
            if ((this.ClearBeforeFill == true)) {
                dataTable.Clear();
            }
            int returnValue = this.Adapter.Fill(dataTable);
            return returnValue;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.Design.HelpKeywordAttribute("vs.data.TableAdapter")]
        [global::System.ComponentModel.DataObjectMethodAttribute(global::System.ComponentModel.DataObjectMethodType.Select, true)]
        public virtual dsRequisicao.ITENS_REQUISICAODataTable GetData() {
            this.Adapter.SelectCommand = this.CommandCollection[0];
            dsRequisicao.ITENS_REQUISICAODataTable dataTable = new dsRequisicao.ITENS_REQUISICAODataTable();
            this.Adapter.Fill(dataTable);
            return dataTable;
        }
    }
}

#pragma warning restore 1591